### ISSUE TITLE
gulp issue

### ISSUE THREAD

**Issue by iijiang** [govau/message-lab-theme#2]
I have never used gulp, seems very sweet to me. However I can not get localhost:3000 working on my local. I got Browsersync working well, I supposed local host should run. Any suggestion? Thanks.

**Comment by iijiang** [comment]
I just had a look gulpfile.js, there is no any task to show anything here, I supposed that''s why?

**Comment by imperator99** [comment]
Hi @iijiang. What exactly is happening when you try to run gulp? You need a Drupal site already set up and running locally for this to do anything, as it proxies an existing site which you can setup via config.yml.

**Comment by iijiang** [comment]
@imperator99, Thanks for reply,  theme is awesome :). 

We are using drupalvm, and drush-make so far. Gulp is pretty new to me,  I was just trying to play around it, which I thought it could auto spinup a style guild or something static.  

I would suggest the doco for the installation might need a bit of clear, what we need gulp for? Like me I pretty much read the readme and tried what I have read from there. 

There is another gap from me. As a uikit theme user, I would like to keep tracking the uikit update, and make the changes under my custom theme, which it not a issue here.

**Comment by imperator99** [comment]
gulp certainly can spin up a static style guide, however this theme doesn't do that (since the style guide is available via the UI Kit). I suggest reading up on [gulp](https://gulpjs.com/) a bit, since it can do an awful lot in terms of automation.

The documentation does assume a user will know what gulp is for, so I will update the documentation to add that clarity.

It also won't update the UI Kit for you; this is done via NPM. However, I believe this is possible via gulp-npm-check so I will look into adding that as well.

**Comment by iijiang** [comment]
Thanks for sharing @imperator99.
